---
title: "Data Analysis on Stanford Open Policing Project Data"
author: "Albert Shin & Seeam Noor"
date: "3/26/2019"
output: html_document
---
```{r seutp, warning = FALSE, error = FALSE, message = FALSE, echo = FALSE}
library(tidyverse)
library(gt)
```

```{r analysis, message=FALSE, echo = FALSE, warning = FALSE}

# Reading an R object as our data

data_main <- read_rds('tr137st9964_ct_hartford_2019_02_25.rds')

data_main %>%
  # Grouping by race and district
  
  group_by(subject_race, district) %>%
  # Only considering when arrests happened
  
  filter(arrest_made == TRUE) %>%
  # Counting the arrests made in each group
  
  count(arrest_made) %>%
  # Ungrouping the data since it helps creating a table using gt function
  
  ungroup() %>%
  select(-arrest_made) %>%
  # Giving appropriate labels to columns
  
  rename("Race" = subject_race, "District" = district) %>%
  spread(key = Race, value = n, fill = 0) %>%
  # Making a table using the GT function
  
  gt() %>%
  tab_header(
      title = "Number of arrests made by race and district")

```

The first day in the data is `r data_main %>% arrange(date) %>% select(date) %>% slice(1)`